# Generated by Django 4.2.2 on 2023-06-22 22:28

from django.db import migrations
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='cpf',
            field=localflavor.br.models.BRCPFField(max_length=14, verbose_name='CPF'),
        ),
        migrations.AlterUniqueTogether(
            name='employer',
            unique_together={('cpf', 'restaurant')},
        ),
    ]
