# Generated by Django 4.2.2 on 2023-06-22 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_employer_cpf_alter_employer_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productcomplement',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
