# Generated by Django 4.2.2 on 2023-06-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_alter_employer_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='codigo_ncm',
            field=models.CharField(blank=True, help_text='Código NCM do produto (8 dígitos).', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='codigo_produto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Product Code'),
        ),
        migrations.AddField(
            model_name='product',
            name='icms_aliquota',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Alíquota do ICMS. Deve estar entre 0 e 100.', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='icms_base_calculo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Base de cálculo do ICMS. Normalmente é igual ao valor_bruto.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='icms_modalidade_base_calculo',
            field=models.CharField(blank=True, choices=[('0', '0 – margem de valor agregado (%)'), ('1', '1 – pauta (valor)'), ('2', '2 – preço tabelado máximo (valor)'), ('3', '3 – valor da operação')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='icms_origem',
            field=models.CharField(blank=True, choices=[('0', '0 - Nacional'), ('1', '1 - Estrangeira - Importação direta'), ('2', '2 - Estrangeira - Adquirida no mercado interno'), ('3', '3 - Nacional, mercadoria ou bem com Conteúdo de Importação superior a 40% e inferior ou igual a 70%'), ('4', '4 - Nacional, cuja produção tenha sido feita em conformidade com os processos produtivos básicos de que tratam as legislações citadas nos Ajustes'), ('5', '5 - Nacional, mercadoria ou bem com Conteúdo de Importação inferior ou igual a 40%'), ('6', '6 - Estrangeira - Importação direta, sem similar nacional, constante em lista da CAMEX e gás natural'), ('7', '7 - Estrangeira - Adquirida no mercado interno, sem similar nacional, constante lista CAMEX e gás natural')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='icms_situacao_tributaria',
            field=models.CharField(blank=True, choices=[('102', '102 – Tributada pelo Simples Nacional sem permissão de crédito'), ('300', '300 - Imune'), ('500', '500 - CMS cobrado anteriormente por substituição tributária (substituído) ou por antecipação'), ('00', '00 – tributada integralmente'), ('40', '40 – Isenta'), ('41', '41 - Não tributada'), ('60', '60 - ICMS cobrado anteriormente por substituição tributária')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_tax_description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='unidade_comercial',
            field=models.CharField(blank=True, choices=[('KG', 'KG'), ('L', 'L'), ('UN', 'UN')], help_text='Unidade comercial do produto. Você pode utilizar valores como “KG”, “L”, “UN”, etc. Caso não se aplique utilize “UN”.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='unidade_tributavel',
            field=models.CharField(blank=True, choices=[('KG', 'KG'), ('L', 'L'), ('UN', 'UN')], help_text='Unidade tributável do produto. Caso não se aplique utilize o mesmo valor do campo unidade_comercial.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='valor_unitario_comercial',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='valor_unitario_tributavel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
