# Generated by Django 4.2.2 on 2023-06-28 22:04

from django.db import migrations, models
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_alter_product_description_alter_product_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='address',
            new_name='complement',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='number',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='state',
            field=localflavor.br.models.BRStateField(default='MA', max_length=2, verbose_name='State'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='street',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='zip_code',
            field=localflavor.br.models.BRPostalCodeField(default='65901350', max_length=9, verbose_name='Zip Code'),
            preserve_default=False,
        ),
    ]
