# Generated by Django 4.2.2 on 2023-06-29 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_catalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=100)),
                ('port', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('paper_width', models.IntegerField(default=80, help_text='valor em mm')),
                ('titleFontSize', models.IntegerField(default=18)),
                ('bodyFontSize', models.IntegerField(default=16)),
                ('footerFontSize', models.IntegerField(default=14)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printers', to='restaurants.restaurant')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='printer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='restaurants.printer'),
        ),
    ]
