# Generated by Django 4.2.2 on 2023-06-28 22:05

from django.db import migrations
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_alter_restaurant_city_alter_restaurant_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='state',
            field=localflavor.br.models.BRStateField(blank=True, max_length=2, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='zip_code',
            field=localflavor.br.models.BRPostalCodeField(blank=True, max_length=9, null=True, verbose_name='Zip Code'),
        ),
    ]
