# Generated by Django 4.2.2 on 2023-06-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_printer_product_printer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcomplement',
            name='description',
        ),
        migrations.RemoveField(
            model_name='productcomplement',
            name='price',
        ),
        migrations.RemoveField(
            model_name='productcomplement',
            name='type',
        ),
        migrations.AddField(
            model_name='product',
            name='complemet_limit',
            field=models.IntegerField(default=0, help_text='Quatidade máxima de complementos que podem ser adicionados ao produto.'),
        ),
        migrations.AddField(
            model_name='product',
            name='type_of_sale',
            field=models.CharField(choices=[('KG', 'KG'), ('L', 'L'), ('UN', 'UN')], default='UN', max_length=3),
        ),
    ]
