# Generated by Django 4.2.2 on 2023-06-28 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_alter_restaurant_state_alter_restaurant_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='complement',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
