# Generated by Django 4.2.2 on 2023-06-29 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_remove_productcomplement_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employer',
            options={'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
    ]
