# Generated by Django 4.2.2 on 2023-06-28 22:19

import apps.restaurants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_alter_restaurant_complement'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.restaurants.models.upload_path, verbose_name='Picture'),
        ),
    ]
