# Generated by Django 4.2.2 on 2023-06-28 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_restaurant_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='slug',
            field=models.SlugField(default='teste', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
