# Generated by Django 4.2.2 on 2023-07-25 02:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_alter_restaurant_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductComplementCategory',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('input_type', models.CharField(choices=[('checkbox', 'checkbox'), ('radio', 'radio'), ('number', 'number')], default='checkbox', max_length=255)),
                ('business_rules', models.TextField(blank=True, choices=[('maior', 'maior'), ('soma', 'soma'), ('media', 'media')], null=True)),
                ('max_value', models.IntegerField(default=0)),
                ('min_value', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complement_categories', to='restaurants.product')),
            ],
            options={
                'verbose_name': 'Product Complement Category',
                'verbose_name_plural': 'Product Complement Categories',
            },
        ),
        migrations.CreateModel(
            name='ProductComplementItem',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_value', models.IntegerField(default=0)),
                ('min_value', models.IntegerField(default=0)),
                ('complementCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complements', to='restaurants.productcomplementcategory')),
            ],
            options={
                'verbose_name': 'Product Complement',
                'verbose_name_plural': 'Product Complements',
            },
        ),
        migrations.DeleteModel(
            name='ProductComplement',
        ),
    ]
