# Generated by Django 4.2.2 on 2023-07-28 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_productcomplementcategory_productcomplementitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='complemet_limit',
        ),
    ]
