# Generated by Django 4.2.2 on 2023-08-08 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0014_alter_productcomplementitem_complementcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='role',
            field=models.CharField(choices=[('GERENTE', 'GERENTE'), ('FUNCIONARIO', 'FUNCIONARIO')], default='FUNCIONARIO', max_length=255),
        ),
    ]
