# Generated by Django 4.2.2 on 2023-08-14 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0018_alter_printer_ip_alter_printer_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cfop',
            field=models.CharField(blank=True, help_text='Código Fiscal de Operações e Prestações (4 dígitos).', max_length=255, null=True),
        ),
    ]
