# Generated by Django 4.2.2 on 2023-08-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0019_product_cfop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='icms_aliquota',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Alíquota do ICMS. Deve estar entre 0 e 100.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='icms_situacao_tributaria',
            field=models.CharField(blank=True, choices=[('102', '102 – Tributada pelo Simples Nacional sem permissão de crédito'), ('300', '300 - Imune'), ('500', '500 - CMS cobrado anteriormente por substituição tributária (substituído) ou por antecipação'), ('00', '00 – tributada integralmente'), ('40', '40 – Isenta'), ('41', '41 - Não tributada'), ('60', '60 - ICMS cobrado anteriormente por substituição tributária'), ('20', '20 – Com redução de base de cálculo')], max_length=255, null=True),
        ),
    ]
