# Generated by Django 4.2.2 on 2023-08-14 15:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0020_alter_product_icms_aliquota_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoRegister',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('csv', models.FileField(blank=True, null=True, upload_to='csv/')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_registers', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Auto Register',
                'verbose_name_plural': 'Auto Registers',
            },
        ),
    ]
