# Generated by Django 4.2.2 on 2023-08-14 16:01

import apps.restaurants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0021_autoregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='autoregister',
            name='csv',
            field=models.FileField(blank=True, null=True, upload_to=apps.restaurants.models.upload_path_csv),
        ),
    ]
