# Generated by Django 4.2.2 on 2023-08-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0022_productcategory_active_alter_autoregister_csv'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='open_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
