# Generated by Django 4.2.2 on 2023-08-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0024_remove_catalog_products_productprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprice',
            name='tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
