# Generated by Django 4.2.2 on 2023-08-20 14:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0026_catalog_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductComplementPrice',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_complement_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='restaurants.productcomplementitem')),
            ],
            options={
                'verbose_name': 'Product complemnet Price',
                'verbose_name_plural': 'Product complement Prices',
                'ordering': ['product_complement_item__title'],
            },
        ),
    ]
