# Generated by Django 4.2.2 on 2023-08-20 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0027_productcomplementprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomplementprice',
            name='product_price',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='complement_prices', to='restaurants.productprice'),
            preserve_default=False,
        ),
    ]
