# Generated by Django 4.2.2 on 2023-08-21 21:51

import apps.restaurants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0031_alter_employer_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.restaurants.models.upload_path_product, verbose_name='photo'),
        ),
    ]
