# Generated by Django 4.2.2 on 2023-08-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0032_product_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcomplementcategory',
            name='product',
        ),
        migrations.AddField(
            model_name='productcomplementcategory',
            name='products',
            field=models.ManyToManyField(related_name='complement_categories', to='restaurants.product'),
        ),
    ]
