# Generated by Django 4.2.2 on 2023-08-27 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0033_remove_productcomplementcategory_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomplementcategory',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complement_categories', to='restaurants.restaurant', null=True),
            preserve_default=False,
        ),
    ]
