# Generated by Django 4.2.2 on 2023-08-27 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0034_productcomplementcategory_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcomplementcategory',
            name='restaurant',
        ),
    ]
