# Generated by Django 4.2.2 on 2023-08-27 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0035_remove_productcomplementcategory_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomplementcategory',
            name='restaurant',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='complement_categories', to='restaurants.restaurant'),
            preserve_default=False,
        ),
    ]
