# Generated by Django 4.2.2 on 2023-08-28 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0036_productcomplementcategory_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='calc_icms_base_calculo',
            field=models.BooleanField(default=False, help_text='Se marcado, o valor da base de cálculo do ICMS será calculado automaticamente.'),
        ),
        migrations.AlterField(
            model_name='productcomplementcategory',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complement_categories', to='restaurants.restaurant'),
        ),
    ]
