# Generated by Django 4.2.2 on 2023-08-31 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0038_complementprice_delete_productcomplementprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complementprice',
            name='catalog',
        ),
        migrations.AddField(
            model_name='catalog',
            name='complement_prices',
            field=models.ManyToManyField(blank=True, related_name='catalogs', to='restaurants.complementprice'),
        ),
        migrations.AddField(
            model_name='complementprice',
            name='tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
