# Generated by Django 4.2.2 on 2023-10-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0040_alter_employer_code_alter_employer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcomplementcategory',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='complement_categories', to='restaurants.product'),
        ),
    ]
