# Generated by Django 4.2.2 on 2023-11-16 12:39

import apps.restaurants.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0042_alter_productcomplementcategory_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoUpdate',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('csv', models.FileField(blank=True, null=True, upload_to=apps.restaurants.models.upload_path_csv)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_updaters', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Auto Update',
                'verbose_name_plural': 'Auto Update',
            },
        ),
    ]
