# Generated by Django 4.2.2 on 2023-12-05 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0044_alter_autoupdate_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='neighborhood',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
