# Generated by Django 4.2.2 on 2023-12-01 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_deliveryorder_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='troco',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Troco'),
        ),
    ]
