# Generated by Django 4.2.2 on 2023-12-03 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0038_payment_type'),
        ('delivery', '0004_deliveryorder_troco'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='payment_group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_order', to='financial.paymentgroup', verbose_name='Payment Group'),
        ),
    ]
