# Generated by Django 4.2.2 on 2023-12-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_deliveryorder_payment_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='canceled',
            field=models.BooleanField(default=False, verbose_name='Canceled'),
        ),
    ]
