# Generated by Django 4.2.2 on 2023-12-05 01:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_deliveryorder_canceled'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryStatus',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(choices=[('WAITING', 'Aguardando confirmação do restaurante'), ('IN_PROGRESS', 'Em produção'), ('IN_ROUTE', 'Saiu para entrega'), ('DELIVERED', 'Saiu para entrega'), ('CANCELED', 'Cancelado')], default='WAITING', max_length=11, verbose_name='Title')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='delivery.deliveryorder', verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Delivery status',
                'verbose_name_plural': 'Delivery status',
                'unique_together': {('title', 'order')},
            },
        ),
    ]
