# Generated by Django 4.2.2 on 2023-12-05 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_deliverystatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='takeaway',
            field=models.BooleanField(default=False, verbose_name='Takeaway'),
        ),
    ]
