# Generated by Django 4.2.2 on 2023-12-05 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_deliveryorder_takeaway'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverystatus',
            name='title',
            field=models.CharField(choices=[('WAITING', 'Aguardando confirmação do restaurante'), ('IN_PROGRESS', 'Em produção'), ('IN_ROUTE', 'Saiu para entrega'), ('DELIVERED', 'Entregue'), ('CANCELED', 'Cancelado')], default='WAITING', max_length=11, verbose_name='Title'),
        ),
    ]
