# Generated by Django 4.2.2 on 2023-12-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_alter_deliverystatus_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverystatus',
            name='position',
            field=models.IntegerField(default=0, verbose_name='Position'),
        ),
    ]
