# Generated by Django 4.2.2 on 2023-12-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0010_deliverystatus_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverystatus',
            name='time',
            field=models.IntegerField(default=0, verbose_name='Hora'),
        ),
    ]
