# Generated by Django 4.2.2 on 2023-10-14 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0042_alter_productcomplementcategory_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='IfoodUserCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('token_type', models.CharField(max_length=255)),
                ('expires_in', models.CharField(max_length=255)),
                ('refresh_token', models.CharField(max_length=255)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ifood_user_credentials', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Ifood user credentials',
                'verbose_name_plural': 'Ifood user credentials',
            },
        ),
    ]
