# Generated by Django 4.2.2 on 2023-10-17 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ifoodusercredentials',
            name='refresh_token',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ifoodusercredentials',
            name='token',
            field=models.TextField(),
        ),
    ]
