# Generated by Django 4.2.2 on 2023-06-29 22:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import localflavor.br.models
import model_utils.fields
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0010_alter_restaurant_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('natureza_operacao', models.CharField(blank=True, default='VENDA AO CONSUMIDOR', max_length=255, null=True, verbose_name='Natureza da operação')),
                ('presenca_comprador', models.CharField(choices=[('1', 'Operação presencial'), ('4', 'Entrega a domicílio')], default='1', max_length=1, verbose_name='Presença do comprador')),
                ('modalidade_frete', models.CharField(choices=[('0', 'Por conta do emitente'), ('1', 'Por conta do destinatário'), ('2', 'Por conta de terceiros'), ('9', 'Sem frete')], default='9', max_length=1, verbose_name='Modalidade do frete')),
                ('local_destino', models.CharField(choices=[('1', 'Operação interna'), ('2', 'Operação interestadual'), ('3', 'Operação com exterior')], default='1', max_length=1, verbose_name='Local de destino')),
                ('cnpj', localflavor.br.models.BRCNPJField(max_length=18, verbose_name='CNPJ')),
                ('nome', models.CharField(max_length=255, verbose_name='Name')),
                ('nome_fantasia', models.CharField(max_length=255, verbose_name='Fantasy name')),
                ('inscricao_estadual', models.PositiveBigIntegerField(verbose_name='Inscrição estadual')),
                ('inscricao_municipal', models.PositiveBigIntegerField(verbose_name='Inscrição municipal')),
                ('regime_tributario', models.CharField(choices=[('1', 'Simples Nacional'), ('2', 'Simples Nacional - Excesso de sublimite de receita bruta'), ('3', 'Regime Normal')], default='1', max_length=1, verbose_name='Regime tributário')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Número de telefone')),
                ('logradouro', models.CharField(max_length=255, verbose_name='Street')),
                ('numero', models.PositiveIntegerField(verbose_name='Number')),
                ('complemento', models.CharField(blank=True, max_length=255, null=True, verbose_name='Complement')),
                ('bairro', models.CharField(max_length=255, verbose_name='Neighborhood')),
                ('cep', localflavor.br.models.BRPostalCodeField(max_length=9, verbose_name='Postal code')),
                ('municipio', models.CharField(max_length=255, verbose_name='City')),
                ('uf', localflavor.br.models.BRStateField(max_length=2, verbose_name='State')),
                ('enviar_email_destinatario', models.BooleanField(default=False, verbose_name='Send email to recipient')),
                ('cpf_cnpj_contabilidade', localflavor.br.models.BRCNPJField(blank=True, max_length=18, null=True, verbose_name='CNPJ of accounting')),
                ('csc_nfce_producao', models.CharField(blank=True, help_text='CSC para emissão de NFCe em ambiente de produção. Sem este campo não será possível emitir NFCe em produção. Veja com o SEFAZ do seu estado como gerar este código.', max_length=36, null=True, verbose_name='CSC NFCE production')),
                ('id_token_nfce_producao', models.CharField(blank=True, help_text='d do CSC para emissão de NFCe em ambiente de produção. Sem este campo não será possível emitir NFCe em produção.Veja com o SEFAZ do seu estado como gerar este número.', max_length=6, null=True, verbose_name='ID Token NFCE production')),
                ('arquivo_certificado_base64', models.TextField(blank=True, help_text='Arquivo do certificado digital em formato base64', null=True, verbose_name='Certificate file')),
                ('senha_certificado', models.CharField(blank=True, help_text='Senha do certificado digital', max_length=255, null=True, verbose_name='Certificate password')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='restaurants.restaurant', verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
