# Generated by Django 4.2.2 on 2023-06-29 22:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import localflavor.br.models
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0013_paymentmethod_method_paymentmethod_restaurant_and_more'),
        ('tax_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_emissao', models.DateTimeField(blank=True, null=True, verbose_name='Emission date')),
                ('emited', models.BooleanField(default=False, verbose_name='Emited')),
                ('ref', models.CharField(blank=True, max_length=255, null=True, verbose_name='External reference')),
                ('status', models.CharField(blank=True, max_length=255, null=True, verbose_name='Status')),
                ('status_sefaz', models.CharField(blank=True, max_length=255, null=True, verbose_name='Status SEFAZ')),
                ('mensagem_sefaz', models.CharField(blank=True, max_length=255, null=True, verbose_name='Message SEFAZ')),
                ('serie', models.CharField(blank=True, max_length=255, null=True, verbose_name='Series')),
                ('numero', models.CharField(blank=True, max_length=255, null=True, verbose_name='Number')),
                ('chave_nfe', models.CharField(blank=True, max_length=255, null=True, verbose_name='NFE key')),
                ('caminho_xml_nota_fiscal', models.CharField(blank=True, max_length=255, null=True, verbose_name='XML path')),
                ('caminho_danfe', models.CharField(blank=True, max_length=255, null=True, verbose_name='DANFE path')),
                ('qrcode_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='QRCode URL')),
                ('url_consulta_nf', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL for consultation')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to='tax_module.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Tax',
                'verbose_name_plural': 'Taxes',
            },
        ),
        migrations.CreateModel(
            name='TaxItems',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_item', models.PositiveIntegerField(verbose_name='Item number')),
                ('quantidade_comercial', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Commercial quantity')),
                ('quantidade_tributavel', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Taxable quantity')),
                ('cfop', models.CharField(max_length=255, verbose_name='CFOP')),
                ('valor_bruto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Gross value')),
                ('valor_desconto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Discount value')),
                ('valor_frete', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Freight value')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_items', to='financial.order', verbose_name='Ordem')),
                ('tax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tax_module.tax', verbose_name='Tax')),
            ],
            options={
                'verbose_name': 'Tax item',
                'verbose_name_plural': 'Tax items',
            },
        ),
        migrations.CreateModel(
            name='PaymentItemsMethods',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Value')),
                ('cnpj_credenciadora', localflavor.br.models.BRCNPJField(blank=True, help_text='Obrigatório se tipo_integracao for 1', max_length=18, null=True, verbose_name='CNPJ of the card operator')),
                ('numero_autorizacao', models.CharField(blank=True, help_text='Obrigatório se tipo_integracao for 1', max_length=255, null=True, verbose_name='Authorization number')),
                ('tipo_integracao', models.CharField(blank=True, choices=[('1', 'Pagamento integrado com o sistema de automação da empresa'), ('2', 'Pagamento não integrado com o sistema de automação da empresa')], help_text='Informar apenas se forma_pagamento for 03 ou 04.', max_length=1, null=True, verbose_name='Integration type')),
                ('bandeira_operadora', models.CharField(blank=True, help_text='Obrigatório se forma_pagamento for cartão', max_length=255, null=True, verbose_name='Flag operator')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_methods', to='financial.payment', verbose_name='Payment')),
                ('tax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_methods', to='tax_module.tax', verbose_name='Tax')),
            ],
            options={
                'verbose_name': 'Payment item method',
                'verbose_name_plural': 'Payment item methods',
            },
        ),
    ]
