# Generated by Django 4.2.2 on 2023-08-14 03:35

from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0018_alter_printer_ip_alter_printer_port'),
        ('tax_module', '0002_tax_taxitems_paymentitemsmethods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='restaurant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to='restaurants.restaurant', verbose_name='Restaurant'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='status',
            field=model_utils.fields.StatusField(choices=[('1', 'Aguardando envio'), ('2', 'Enviado'), ('3', 'Cancelado'), ('4', 'Erro'), ('5', 'Autorizado')], default='1', max_length=100, no_check_for_status=True, verbose_name='Status'),
        ),
    ]
