# Generated by Django 4.2.2 on 2023-08-14 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0018_alter_printer_ip_alter_printer_port'),
        ('tax_module', '0003_alter_company_restaurant_alter_tax_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='restaurant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='restaurants.restaurant', verbose_name='Restaurant'),
        ),
    ]
