# Generated by Django 4.2.2 on 2023-08-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_module', '0004_alter_company_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxitems',
            name='cfop',
        ),
        migrations.RemoveField(
            model_name='taxitems',
            name='numero_item',
        ),
        migrations.RemoveField(
            model_name='taxitems',
            name='order',
        ),
        migrations.AddField(
            model_name='tax',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Link'),
        ),
    ]
