# Generated by Django 4.2.2 on 2023-10-06 11:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0042_alter_productcomplementcategory_products'),
        ('inventory', '0002_alter_itemtransaction_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='relatedProducts',
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=100, verbose_name='Quantity')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='inventory.item', verbose_name='Item')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='restaurants.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product item',
                'verbose_name_plural': 'Product items',
            },
        ),
        migrations.CreateModel(
            name='ItemItem',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=100, verbose_name='Quantity')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.item', verbose_name='Item')),
                ('item_related', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_related', to='inventory.item', verbose_name='Item related')),
            ],
            options={
                'verbose_name': 'Item item',
                'verbose_name_plural': 'Item items',
            },
        ),
    ]
