# Generated by Django 4.2.2 on 2023-10-06 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0005_alter_item_minimum_stock_alter_item_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtransaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
