# Generated by Django 4.2.2 on 2023-06-29 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0007_printer_product_printer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cashier',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('open', models.BooleanField(default=True, verbose_name='Open')),
                ('initial_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Initial value')),
                ('opened_by_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Opened by')),
                ('closed_by_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Closed by')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Closed at')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=models.SET('Usuário deletado'), related_name='cashier_closed_by', to=settings.AUTH_USER_MODEL, verbose_name='Closed by')),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=models.SET('Usuário deletado'), related_name='cashier_opened_by', to=settings.AUTH_USER_MODEL, verbose_name='Opened by')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashiers', to='restaurants.restaurant', verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Cashier',
                'verbose_name_plural': 'Cashiers',
                'ordering': ['-created'],
            },
        ),
    ]
