# Generated by Django 4.2.2 on 2023-06-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashier',
            name='identifier',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Identifier'),
        ),
    ]
