# Generated by Django 4.2.2 on 2023-06-29 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_printer_product_printer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financial', '0002_cashier_identifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.IntegerField(verbose_name='Number')),
                ('open', models.BooleanField(default=True, verbose_name='Open')),
                ('client_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Client name')),
                ('client_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='BR', verbose_name='Phone')),
                ('opened_by_name', models.CharField(max_length=255, verbose_name='Opened by')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='financial.cashier', verbose_name='Cashier')),
                ('opened_by', models.ForeignKey(on_delete=models.SET('Usuário deletado'), related_name='bill_opened_by', to=settings.AUTH_USER_MODEL, verbose_name='Opened by')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='restaurants.table', verbose_name='Table')),
            ],
            options={
                'verbose_name': 'Bill',
                'verbose_name_plural': 'Bills',
                'ordering': ['-created'],
                'unique_together': {('number', 'cashier')},
            },
        ),
    ]
