# Generated by Django 4.2.2 on 2023-06-29 18:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_remove_productcomplement_description_and_more'),
        ('financial', '0003_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_title', models.CharField(max_length=255, verbose_name='Product title')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Price')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Nota')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='financial.bill', verbose_name='Bill')),
                ('product', models.ForeignKey(on_delete=models.SET('produto excluido'), related_name='orders', to='restaurants.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Ordem',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created'],
            },
        ),
    ]
