# Generated by Django 4.2.2 on 2023-06-29 19:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0004_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.IntegerField(default=0, verbose_name='Ordem')),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Tax percentage')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tax')),
                ('payout_schedule', models.IntegerField(default=0, help_text='Number of days to receive the payment', verbose_name='Payout schedule')),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='tip',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tip'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_method_title', models.CharField(max_length=255, verbose_name='Payment Method title')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Value')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Nota')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='financial.bill', verbose_name='Bill')),
                ('payment_method', models.ForeignKey(on_delete=models.SET('Método de pagamento excluído'), related_name='payments', to='financial.paymentmethod', verbose_name='Payment Method')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
