# Generated by Django 4.2.2 on 2023-06-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0005_paymentmethod_bill_tip_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Order Number'),
        ),
    ]
