# Generated by Django 4.2.2 on 2023-06-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0009_alter_bill_opened_by_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='opened_by_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Opened by'),
        ),
    ]
