# Generated by Django 4.2.2 on 2023-08-04 03:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0014_alter_productcomplementitem_complementcategory'),
        ('financial', '0013_paymentmethod_method_paymentmethod_restaurant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderComplement',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('complement_item_title', models.CharField(max_length=255, verbose_name='Complement Item title')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Price')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Nota')),
                ('complement_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_complements', to='restaurants.productcomplementitem', verbose_name='Complement Item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complements', to='financial.order', verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Order Complement',
                'verbose_name_plural': 'Order Complements',
                'ordering': ['-created'],
                'unique_together': {('order', 'complement_item')},
            },
        ),
    ]
