# Generated by Django 4.2.2 on 2023-08-04 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0014_ordercomplement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='order',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Unit Price'),
        ),
    ]
