# Generated by Django 4.2.2 on 2023-08-04 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0015_alter_order_quantity_alter_order_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
        migrations.AlterField(
            model_name='ordercomplement',
            name='complement_item_title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Complement Item title'),
        ),
        migrations.AlterField(
            model_name='ordercomplement',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='ordercomplement',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='ordercomplement',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Unit Price'),
        ),
    ]
