# Generated by Django 4.2.2 on 2023-08-04 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0016_remove_order_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordercomplement',
            name='note',
        ),
    ]
