# Generated by Django 4.2.2 on 2023-08-08 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0019_alter_bill_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bill',
            unique_together=set(),
        ),
    ]
