# Generated by Django 4.2.2 on 2023-08-08 21:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0017_employer_sidebar_permissions'),
        ('financial', '0020_alter_bill_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordercomplement',
            options={'ordering': ['-created'], 'verbose_name': 'Order Complement', 'verbose_name_plural': 'Order Complement'},
        ),
        migrations.AlterUniqueTogether(
            name='ordercomplement',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ordercomplement',
            name='complement_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_complements', to='restaurants.productcomplementcategory', verbose_name='Complement Item'),
        ),
        migrations.AddField(
            model_name='ordercomplement',
            name='complement_group_title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Complement Item title'),
        ),
        migrations.AlterUniqueTogether(
            name='ordercomplement',
            unique_together={('order', 'complement_group')},
        ),
        migrations.RemoveField(
            model_name='ordercomplement',
            name='complement_item',
        ),
        migrations.RemoveField(
            model_name='ordercomplement',
            name='complement_item_title',
        ),
        migrations.RemoveField(
            model_name='ordercomplement',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='ordercomplement',
            name='unit_price',
        ),
        migrations.CreateModel(
            name='OrderComplementItem',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('complement_title', models.CharField(blank=True, default='', max_length=255, verbose_name='Complement title')),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Unit Price')),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Total')),
                ('complement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_complements', to='restaurants.productcomplementitem', verbose_name='Complement')),
                ('order_complement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='financial.ordercomplement', verbose_name='Order Complement')),
            ],
            options={
                'verbose_name': 'Order Complement Item',
                'verbose_name_plural': 'Order Complement Items',
                'ordering': ['-created'],
                'unique_together': {('order_complement', 'complement')},
            },
        ),
    ]
