# Generated by Django 4.2.2 on 2023-08-08 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0021_alter_ordercomplement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Total'),
        ),
    ]
