# Generated by Django 4.2.2 on 2023-08-09 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0017_employer_sidebar_permissions'),
        ('financial', '0022_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='colaborator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='restaurants.employer', verbose_name='Colaborator'),
        ),
    ]
