# Generated by Django 4.2.2 on 2023-08-09 02:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import localflavor.br.models
import model_utils.fields
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0017_employer_sidebar_permissions'),
        ('financial', '0023_order_colaborator'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderGroup',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('DELIVERY', 'DELIVERY'), ('TAKEOUT', 'TAKEOUT'), ('TABLE', 'TABLE'), ('BILL', 'BILL')], default='BILL', max_length=255, verbose_name='Type')),
                ('order_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Order Number')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
                ('collaborator_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Colaborator name')),
                ('Table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_groups', to='restaurants.table', verbose_name='Table')),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_groups', to='financial.bill', verbose_name='Bill')),
                ('collaborator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='restaurants.employer', verbose_name='Colaborator')),
            ],
            options={
                'verbose_name': 'Order Group',
                'verbose_name_plural': 'Order Groups',
                'ordering': ['-created'],
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='order',
            name='colaborator',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_number',
        ),
        migrations.CreateModel(
            name='TakeoutOrder',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Client name')),
                ('client_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='BR', verbose_name='Phone')),
                ('cpf', localflavor.br.models.BRCPFField(blank=True, max_length=14, null=True, verbose_name='CPF')),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('PAID', 'PAID'), ('CANCELED', 'CANCELED')], default='OPEN', max_length=255, verbose_name='Status')),
                ('order_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='takeout_order', to='financial.ordergroup', verbose_name='Order Group')),
            ],
            options={
                'verbose_name': 'Takeout',
                'verbose_name_plural': 'Takeouts',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255, verbose_name='Status')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_status', to='restaurants.restaurant', verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Order Status',
                'verbose_name_plural': 'Order Status',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='ordergroup',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_groups', to='financial.orderstatus', verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='financial.ordergroup', verbose_name='Order Group'),
            preserve_default=False,
        ),
    ]
