# Generated by Django 4.2.2 on 2023-08-09 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0024_ordergroup_remove_order_bill_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordergroup',
            name='Table',
        ),
    ]
