# Generated by Django 4.2.2 on 2023-08-09 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0017_employer_sidebar_permissions'),
        ('financial', '0025_remove_ordergroup_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergroup',
            name='restaurant',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='order_groups', to='restaurants.restaurant', verbose_name='Restaurant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordergroup',
            name='type',
            field=models.CharField(choices=[('DELIVERY', 'DELIVERY'), ('TAKEOUT', 'TAKEOUT'), ('BILL', 'BILL')], default='BILL', max_length=255, verbose_name='Type'),
        ),
        migrations.AlterUniqueTogether(
            name='ordergroup',
            unique_together={('order_number', 'restaurant')},
        ),
    ]
