# Generated by Django 4.2.2 on 2023-08-09 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0026_ordergroup_restaurant_alter_ordergroup_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem'),
        ),
    ]
