# Generated by Django 4.2.2 on 2023-08-11 02:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0028_alter_orderstatus_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGroup',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('DELIVERY', 'DELIVERY'), ('TAKEOUT', 'TAKEOUT'), ('BILL', 'BILL')], max_length=255, verbose_name='Type')),
                ('tip', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tip')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
            ],
            options={
                'verbose_name': 'Payment Group',
                'verbose_name_plural': 'Payments Groups',
                'ordering': ['-created'],
            },
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.RemoveField(
            model_name='payment',
            name='bill',
        ),
        migrations.AddField(
            model_name='bill',
            name='payment_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='financial.paymentgroup', verbose_name='Payment Group'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_group',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='financial.paymentgroup', verbose_name='Payment Group'),
            preserve_default=False,
        ),
    ]
