# Generated by Django 4.2.2 on 2023-08-11 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0029_paymentgroup_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='takeoutorder',
            name='cashier',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='takeout_orders', to='financial.cashier', verbose_name='Cashier'),
            preserve_default=False,
        ),
    ]
