# Generated by Django 4.2.2 on 2023-08-21 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0032_product_photo'),
        ('financial', '0031_paymentgroup_cashier'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paymentmethod',
            unique_together={('restaurant', 'title')},
        ),
    ]
