# Generated by Django 4.2.2 on 2023-11-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0035_takeoutorder_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Color'),
        ),
    ]
