# Generated by Django 4.2.2 on 2023-11-15 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0036_orderstatus_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergroup',
            name='cashier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_groups', to='financial.cashier', verbose_name='Cashier'),
        ),
    ]
