# Generated by Django 4.2.2 on 2023-11-16 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0037_ordergroup_cashier'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('PAYMENT', 'ENTRADA'), ('REFUND', 'REENBOLSO'), ('CHARGEBACK', 'TROCO'), ('WITHDRAW', 'SANAGRIA')], default='PAYMENT', max_length=255, verbose_name='Type'),
        ),
    ]
