# Generated by Django 4.2.2 on 2023-12-03 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0044_alter_autoupdate_restaurant'),
        ('financial', '0038_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.CreateModel(
            name='CancelationReason',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('type', models.CharField(choices=[('ORDER', 'Pedido'), ('BILL', 'Comanda')], default='ORDER', max_length=255, verbose_name='Type')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Reason')),
                ('product_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Product title')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelation_reasons', to=settings.AUTH_USER_MODEL, verbose_name='Operator')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelation_reasons', to='restaurants.product', verbose_name='Product')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancelation_reasons', to='restaurants.restaurant', verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Cancelation Reason',
                'verbose_name_plural': 'Cancelation Reasons',
                'ordering': ['-created'],
            },
        ),
    ]
