# Generated by Django 4.2.2 on 2024-02-07 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0040_paymentmethod_acept_on_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancelationreason',
            name='cashier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelation_reasons', to='financial.cashier', verbose_name='Cashier'),
        ),
    ]
