# Generated by Django 4.2.2 on 2024-02-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0041_cancelationreason_cashier'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancelationreason',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='Quantity'),
        ),
    ]
