# Generated by Django 4.2.2 on 2024-02-07 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0042_cancelationreason_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancelationreason',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelation_reasons', to='financial.bill', verbose_name='Bill'),
        ),
    ]
