# Generated by Django 4.2.2 on 2024-04-03 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0043_cancelationreason_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancelationreason',
            name='bill_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Bill number'),
        ),
        migrations.AddField(
            model_name='cancelationreason',
            name='operator_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Operator name'),
        ),
    ]
